# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'FrasesChuckNorris' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Pods for FrasesChuckNorris

  target 'FrasesChuckNorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FrasesChuckNorrisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
